// 单个任务连续达成的 图片资源
export default class ContinueMapInfo {
  off__3: Resource = $r('app.media.ic_continue_3__off');
  on__3: Resource = $r('app.media.ic_continue_3__on');
  off__30: Resource = $r('app.media.ic_continue_30__off');
  on__30: Resource = $r('app.media.ic_continue_30__on');
  off__90: Resource = $r('app.media.ic_continue_90__off');
  on__90: Resource = $r('app.media.ic_continue_90__on');
}