// 单个任务完成率的 图片资源
export default class DegreeMapInfo {
  off__200: Resource = $r('app.media.ic_degree_200__off');
  on__200: Resource = $r('app.media.ic_degree_200__on');
  off__300: Resource = $r('app.media.ic_degree_300__off');
  on__300: Resource = $r('app.media.ic_degree_300__on');
  off__400: Resource = $r('app.media.ic_degree_400__off');
  on__400: Resource = $r('app.media.ic_degree_400__on');
}